accent = "#2E7D4A"
cursor = "#6FE685"
foreground = "#00ff99"
background = "#090a08"
selection_foreground = "#000000"
selection_background = "#59CF77"

color0 = "#02160C"
color1 = "#3DA862"
color2 = "#59CF77"
color3 = "#6FE685"
color4 = "#2E7D4A"
color5 = "#4DB866"
color6 = "#2E7D4A"
color7 = "#45C569"
color8 = "#1F5A3A"
color9 = "#52D374"
color10 = "#59CF77"
color11 = "#6FE685"
color12 = "#5BCF73"
color13 = "#4DB866"
color14 = "#59CF77"
color15 = "#6FE685"
